[2023-02-20 01:27:16,167] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: autoetl-coordinates.get_mapping manual__2023-02-20T01:26:43.088895+00:00 [queued]>
[2023-02-20 01:27:16,179] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: autoetl-coordinates.get_mapping manual__2023-02-20T01:26:43.088895+00:00 [queued]>
[2023-02-20 01:27:16,180] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-20 01:27:16,181] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-02-20 01:27:16,182] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-20 01:27:16,199] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_mapping> on 2023-02-20 01:26:43.088895+00:00
[2023-02-20 01:27:16,208] {standard_task_runner.py:52} INFO - Started process 5798 to run task
[2023-02-20 01:27:16,214] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'autoetl-coordinates', 'get_mapping', 'manual__2023-02-20T01:26:43.088895+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/autoetl-coordinates.py', '--cfg-path', '/tmp/tmpfob1mlrm', '--error-file', '/tmp/tmpm60zivrq']
[2023-02-20 01:27:16,216] {standard_task_runner.py:80} INFO - Job 31: Subtask get_mapping
[2023-02-20 01:27:16,295] {task_command.py:369} INFO - Running <TaskInstance: autoetl-coordinates.get_mapping manual__2023-02-20T01:26:43.088895+00:00 [running]> on host 83ee186d463f
[2023-02-20 01:27:16,409] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=autoetl-coordinates
AIRFLOW_CTX_TASK_ID=get_mapping
AIRFLOW_CTX_EXECUTION_DATE=2023-02-20T01:26:43.088895+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-20T01:26:43.088895+00:00
[2023-02-20 01:27:16,412] {logging_mixin.py:115} INFO - Load Data
[2023-02-20 01:27:18,304] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:189 DtypeWarning: Columns (13,14,16,22) have mixed types.Specify dtype option on import or set low_memory=False.
[2023-02-20 01:28:24,670] {logging_mixin.py:115} INFO - Load mapping config
[2023-02-20 01:28:24,753] {logging_mixin.py:115} INFO - User Guide: https://docs.kepler.gl/docs/keplergl-jupyter
[2023-02-20 01:28:50,504] {logging_mixin.py:115} INFO - Map saved to ./data/outputs/newgeo_map.html!
[2023-02-20 01:28:51,012] {python.py:173} INFO - Done. Returned value was: None
[2023-02-20 01:28:51,062] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=autoetl-coordinates, task_id=get_mapping, execution_date=20230220T012643, start_date=20230220T012716, end_date=20230220T012851
[2023-02-20 01:28:51,276] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-02-20 01:28:51,349] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
