[2023-02-20 02:15:08,275] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: autoetl-coordinates.get_mapping manual__2023-02-20T01:33:39.314319+00:00 [queued]>
[2023-02-20 02:15:08,289] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: autoetl-coordinates.get_mapping manual__2023-02-20T01:33:39.314319+00:00 [queued]>
[2023-02-20 02:15:08,291] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-20 02:15:08,292] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-02-20 02:15:08,293] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-20 02:15:08,308] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_mapping> on 2023-02-20 01:33:39.314319+00:00
[2023-02-20 02:15:08,317] {standard_task_runner.py:52} INFO - Started process 6943 to run task
[2023-02-20 02:15:08,322] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'autoetl-coordinates', 'get_mapping', 'manual__2023-02-20T01:33:39.314319+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/autoetl-coordinates.py', '--cfg-path', '/tmp/tmpum2c7r7q', '--error-file', '/tmp/tmp8cyeewgv']
[2023-02-20 02:15:08,324] {standard_task_runner.py:80} INFO - Job 35: Subtask get_mapping
[2023-02-20 02:15:08,398] {task_command.py:369} INFO - Running <TaskInstance: autoetl-coordinates.get_mapping manual__2023-02-20T01:33:39.314319+00:00 [running]> on host 83ee186d463f
[2023-02-20 02:15:08,483] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=autoetl-coordinates
AIRFLOW_CTX_TASK_ID=get_mapping
AIRFLOW_CTX_EXECUTION_DATE=2023-02-20T01:33:39.314319+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-20T01:33:39.314319+00:00
[2023-02-20 02:15:08,486] {logging_mixin.py:115} INFO - Load Data
[2023-02-20 02:15:10,585] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:189 DtypeWarning: Columns (13,14,16,22) have mixed types.Specify dtype option on import or set low_memory=False.
[2023-02-20 02:15:59,376] {logging_mixin.py:115} INFO - Load mapping config
[2023-02-20 02:15:59,409] {logging_mixin.py:115} INFO - User Guide: https://docs.kepler.gl/docs/keplergl-jupyter
[2023-02-20 02:16:17,839] {logging_mixin.py:115} INFO - Map saved to ./data/outputs/newgeo_map.html!
[2023-02-20 02:16:17,941] {python.py:173} INFO - Done. Returned value was: None
[2023-02-20 02:16:17,964] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=autoetl-coordinates, task_id=get_mapping, execution_date=20230220T013339, start_date=20230220T021508, end_date=20230220T021617
[2023-02-20 02:16:18,096] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-02-20 02:16:18,134] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
