[2023-02-19 14:53:21,667] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: autoetl-coordinates.convert_geojson manual__2023-02-19T14:52:40.561696+00:00 [queued]>
[2023-02-19 14:53:21,680] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: autoetl-coordinates.convert_geojson manual__2023-02-19T14:52:40.561696+00:00 [queued]>
[2023-02-19 14:53:21,681] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-19 14:53:21,682] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-02-19 14:53:21,684] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-19 14:53:21,703] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): convert_geojson> on 2023-02-19 14:52:40.561696+00:00
[2023-02-19 14:53:21,716] {standard_task_runner.py:52} INFO - Started process 706 to run task
[2023-02-19 14:53:21,734] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'autoetl-coordinates', 'convert_geojson', 'manual__2023-02-19T14:52:40.561696+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/autoetl-coordinates.py', '--cfg-path', '/tmp/tmpsfxez5kz', '--error-file', '/tmp/tmptpswcx_k']
[2023-02-19 14:53:21,736] {standard_task_runner.py:80} INFO - Job 9: Subtask convert_geojson
[2023-02-19 14:53:21,807] {task_command.py:369} INFO - Running <TaskInstance: autoetl-coordinates.convert_geojson manual__2023-02-19T14:52:40.561696+00:00 [running]> on host 28bff766bd86
[2023-02-19 14:53:21,887] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=autoetl-coordinates
AIRFLOW_CTX_TASK_ID=convert_geojson
AIRFLOW_CTX_EXECUTION_DATE=2023-02-19T14:52:40.561696+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-19T14:52:40.561696+00:00
[2023-02-19 14:53:21,890] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-02-19 14:53:21,896] {subprocess.py:74} INFO - Running command: ['bash', '-c', '#!/usr/bin/env sh\n\n# Install converter\nnpm install -g geojson2ndjson\n\ncd data\n\n# Convert File\nndjson2geojson ms_hinds_parcels.ndgeojson > ms_hinds_parcels.geojson']
[2023-02-19 14:53:21,914] {subprocess.py:85} INFO - Output:
[2023-02-19 14:53:21,930] {subprocess.py:92} INFO - bash: line 4: npm: command not found
[2023-02-19 14:53:21,932] {subprocess.py:92} INFO - bash: line 6: cd: data: No such file or directory
[2023-02-19 14:53:21,935] {subprocess.py:92} INFO - bash: line 9: ndjson2geojson: command not found
[2023-02-19 14:53:21,936] {subprocess.py:96} INFO - Command exited with return code 127
[2023-02-19 14:53:21,955] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-02-19 14:53:21,962] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=autoetl-coordinates, task_id=convert_geojson, execution_date=20230219T145240, start_date=20230219T145321, end_date=20230219T145321
[2023-02-19 14:53:21,974] {standard_task_runner.py:97} ERROR - Failed to execute job 9 for task convert_geojson (Bash command failed. The command returned a non-zero exit code 127.; 706)
[2023-02-19 14:53:21,986] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-19 14:53:22,031] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
